module.exports = {
    AuthController: require('./auth.controller'),
    ClinicController: require('./clinic.controller'),
    ClinicHistoryController: require('./clinic_history.controller'),
    ExpedientController: require('./expedient.controller'),
    HomeController: require('./home.controller'),
    HospitalController: require('./hospital.controller'),
    OfficeClinicController: require('./office_clinic.controller'),
    OfficeHospitalController: require('./office_hospital.controller'),
    PatientController: require('./patient.controller'),
    PatientHospitalController: require('./patient_hospital.controller'),
    PersonalController: require('./personal.controller'),
    PersonalTypeController: require('./personal_type.controller'),
    SpecialtyController: require('./specialty.controller'),
    UserController: require('./user.controller'),
}